apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfg-backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfg-backend
  template:
    metadata:
      labels:
        app: tfg-backend
    spec:
      containers:
        # Contenedor de php
        - name: php-container
          image: bego13/tfg-php:latest
          env:
            # cojemos del secret.yaml la url de la rds
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: tfg-db-secret
                  key: DATABASE_URL
              #Aplicacion en produccion
            - name: APP_ENV
              value: "prod"
            - name: JWT_PASSPHRASE
              value: "ce5880c03aacade6d7b3f67e3dc46123983219bbde8515593dc7f1b5eeca985b"
          #Para el volumen EFS para las imagenes/videos...
          volumeMounts:
            - name: uploads
              mountPath: /var/www/symfony/public/uploads
        
        # Contenedor del servidor Nginx que sirve al Back
        - name: nginx-back-container
          image: bego13/tfg-nginx-back:latest
          ports:
            - containerPort: 80
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: tfg-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tfg-backend-service
spec:
  selector:
    app: tfg-backend # Debe coincidir exactamente con el label del Deployment
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 80 # Puerto donde escucha Symfony (el que pusimos en Docker)
  type: ClusterIP      # solo visible dentro del clúster, es decir solo el frontend podra acceder a el (back)