apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
mountOptions:
  - tls

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tfg-uploads-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    # ID del efs
    volumeHandle: fs-07d213240a328a2ad

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tfg-uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi