apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
# Le dice que use el driver CSI de EFS que instalamos en el clúster
provisioner: efs.csi.aws.com
mountOptions:
  - tls

---

# Representa el disco real al sistema de archivos que nos vamos a conectar (EFS de AWS con el id fs-...)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tfg-uploads-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    # ID del efs
    volumeHandle: fs-0ff7fc7b9507295a9

---

# La petición que hace el pod para usar el volumen
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tfg-uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi