# Secret para la conexion con la rds, ya que el archivo .env es solo para local
apiVersion: v1
kind: Secret
metadata:
  name: tfg-db-secret
type: Opaque
stringData:
  DATABASE_URL: "mysql://admin:awsrdspassword@database-tfg.cpkysee28b5r.us-east-1.rds.amazonaws.com:3306/tfg_adiestramiento_canino?serverVersion=8.0.46&charset=utf8mb4"
  # DATABASE_URL: "mysql://admin:awsrdspassword@endpoint de la rds:3306/tfg_adiestramiento_canino?serverVersion=8.0.46&charset=utf8mb4"