vich_uploader:
    db_driver: orm

    mappings:
        # Mapeo para los DUEÑOS
        user_images:
            uri_prefix: /uploads/users
            upload_destination: '%kernel.project_dir%/public/uploads/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        # Mapeo para los PERROS
        dog_images:
            uri_prefix: /uploads/dogs
            upload_destination: '%kernel.project_dir%/public/uploads/dogs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        # En proceso...
        # Mapeo para el CAROUSEL
        carousel_media:
            uri_prefix: /uploads/carousel
            upload_destination: '%kernel.project_dir%/public/uploads/carousel'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        # Mapeo para la GALERÍA
        gallery_images:
            uri_prefix: /uploads/gallery
            upload_destination: '%kernel.project_dir%/public/uploads/gallery'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer