events {}

http {

    #include       mime.types;
    #default_type  application/octet-stream;

    server {
        listen 80;
        client_max_body_size 50M;
        server_name localhost;
        root /var/www/symfony/public;
        index index.php;

        # Manda las peticiones al index.php
        location / {
            try_files $uri /index.php$is_args$args;
        }

        # Aqui es donde se "traduce" el código php para que se pueda leer
        location ~ ^/index\.php(/|$) {
            # Aquí "localhost" funciona ya que vamos a meter las dos imagenes de Docker en un mismo pod
            fastcgi_pass 127.0.0.1:9000; 
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $document_root;
            internal;
        }

        # Bloquear acceso a archivos sensibles
        location ~ /\.ht {
            deny all;
        }
    }
}